<?php 
    // Mail Message
    $message = "Welcome to Alapaap Portal,<br><br>".
    "Please use this credential for your access to this link <a href='http://".$_SERVER['SERVER_NAME']."'>https://alapaap.bsp.gov.ph/</a> <br><br>".
    "Email: <b>".$email_add."</b><br>".
    "Temporary Password: <b>".$_POST['pass']."</b><br><br><br>".
    "<i>This message is autogenerated. Please do not respond.</i>"; 
?>

