<?php 
    // Mail Message
    $message = "Dear <b>New User:</b>. <br><br>".
    "You've been invited in Alapaap Portal, Please used this credentials to activate your account.<br><br>".
    "Email: <b>".$email_add."</b><br>".
    "Password: <b>".$_POST['pass']."</b><br><br>".
    "Visit this portal http://".$_SERVER['SERVER_NAME']."".
    "<br><br><br><i>This email is autogenerated Please do not reply!</i>"; 
?>