<?php 
    // Mail Message
    if($status == 2){$stat_name = 'Approver'; $department_name = "BSP"; }
    if($status == 3){$stat_name = 'Receiver'; $department_name = "eBizolution"; }
    if($status == 4){$stat_name = 'Performer'; $department_name = "eBizolution"; }
    if($status == 5){$stat_name = 'Confirmer'; $department_name = "BSP";}
    if($status == 6){$stat_name = 'Verifier'; $department_name = "eBizolution";}
    if($status == 7){$stat_name = 'Requestor'; $department_name = "BSP";}


    if($status >=2 && $status <=6){
        $message = "Dear <b>".$stat_name.":</b>. <br><br>".
        "<b>".ucwords($fullname)."</b> has been requested for <b>HCI New</b> with Control No: <b>HCI/".$control_number."</b><br><br>".
        "Thank you<br><br><br><br><i>This email is autogenerated Please do not reply!</i>"; 
    }else{
        $message = "Dear <b>".$stat_name.":</b>. <br><br>".
        "<b>".ucwords($fullname)."</b> your <b>HCI New</b> form with Control No: <b>HCI/".$control_number."</b> ".
        "has been fully verified by our highest authority".
        "Thank you<br><br><br><br><i>This email is autogenerated Please do not reply!</i>"; 
    }
    
?>